import test from 'node:test';import assert from 'node:assert/strict';
import {signedArea,perimeter,validate,overlap,pointLocation,segmentEnters,onSegment,interiorPoint,intersects} from '../apps/smart-home/src/app/editor/geometry.js';
const p=(x,y)=>({x,y}),box=(x=0,y=0,w=10000,h=8000)=>[p(x,y),p(x+w,y),p(x+w,y+h),p(x,y+h)];
test('10 by 8 metre footprint is 80 m² and 36 m',()=>{assert.equal(signedArea(box())/1e6,80);assert.equal(perimeter(box())/1000,36);assert.equal(validate(box()),null)});
test('clockwise orientation retains absolute area',()=>assert.equal(signedArea(box().reverse())/1e6,-80));
test('fewer than three points cannot close',()=>assert.ok(validate([p(0,0),p(4,0)])));
test('zero area and repeated vertices are invalid',()=>{assert.ok(validate([p(0,0),p(1,0),p(2,0)]));assert.ok(validate([p(0,0),p(0,0),p(1,1)]))});
test('self intersection is rejected',()=>assert.ok(validate([p(0,0),p(100,100),p(0,100),p(100,0)])));
test('separate contours are allowed',()=>assert.equal(overlap(box(),box(15000,0)),false));
test('common boundary is allowed',()=>assert.equal(overlap(box(),box(10000,0)),false));
test('single corner contact is allowed',()=>assert.equal(overlap(box(),box(10000,8000)),false));
test('overlapping area is rejected both ways',()=>{assert.equal(overlap(box(),box(9000,7000)),true);assert.equal(overlap(box(9000,7000),box()),true)});
test('contained contours are rejected',()=>{assert.equal(overlap(box(),box(2000,2000,1000,1000)),true);assert.equal(overlap(box(2000,2000,1000,1000),box()),true)});
test('coincident contours are rejected',()=>assert.equal(overlap(box(),box()),true));
test('point classification distinguishes edge, inside, outside',()=>{assert.equal(pointLocation(p(1,1),box()),1);assert.equal(pointLocation(p(0,1),box()),0);assert.equal(pointLocation(p(-1,1),box()),-1)});
test('segment entering through opposite corners is rejected',()=>assert.equal(segmentEnters(p(-1000,-800),p(11000,8800),box()),true));
test('following a boundary does not enter its interior',()=>assert.equal(segmentEnters(p(0,0),p(10000,0),box()),false));
test('concave L contour has an interior point',()=>{let ps=[p(0,0),p(6,0),p(6,2),p(2,2),p(2,6),p(0,6)];assert.equal(validate(ps),null);assert.equal(signedArea(ps),20);assert.equal(pointLocation(interiorPoint(ps),ps),1)});
test('rotation preserves area and perimeter',()=>{let a=.7853981633974483,ps=box().map(q=>p(q.x*Math.cos(a)-q.y*Math.sin(a),q.x*Math.sin(a)+q.y*Math.cos(a)));assert.ok(Math.abs(signedArea(ps)-8e7)<1e-5);assert.ok(Math.abs(perimeter(ps)-36000)<1e-5);assert.equal(validate(ps),null)});
test('large origin does not destabilise area calculation',()=>assert.equal(signedArea(box(1e9,1e9)),8e7));
test('line projection checks endpoints and collinearity',()=>{assert.equal(onSegment(p(0,0),p(10,10),p(5,5)),true);assert.equal(onSegment(p(0,0),p(10,10),p(5,6)),false);assert.equal(intersects(p(0,0),p(10,10),p(0,10),p(10,0)),true)});
