import {test,expect,Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(()=>(window as any).smartHomeEditor.getState());
async function login(page:Page){await page.goto('/');await page.locator('#login').fill('juralab');await page.locator('#password').fill('juralab');await page.getByRole('button',{name:'Войти',exact:true}).click();await expect(page).toHaveURL(/#\/projects$/)}
async function project(page:Page){await login(page);await page.getByRole('button',{name:'Новый проект',exact:true}).click();await expect(page.locator('#canvas canvas')).toBeVisible();await expect.poll(()=>page.evaluate(()=>!!(window as any).smartHomeEditor)).toBe(true)}
async function tool(page:Page,kind='graphical'){await page.locator('#contourTool').click();await page.locator(kind==='graphical'?'#graphicalTool':'#rectangleTool').click()}
async function origin(page:Page,x=0,y=0){await page.locator('#originX').fill(String(x));await page.locator('#originY').fill(String(y));await page.locator('#originY').press('Enter');await expect.poll(async()=>(await state(page)).points.length).toBe(1)}
async function line(page:Page,key:string,value:number,enter='Enter'){await page.keyboard.press(key);await page.locator('#lineLength').fill(String(value));await page.locator('#lineLength').press(enter)}
async function footprint(page:Page,x=0,y=0){await tool(page);await origin(page,x,y);await line(page,'ArrowRight',10000);await line(page,'ArrowUp',8000);await line(page,'ArrowLeft',10000);await page.keyboard.press('c');await expect.poll(async()=>(await state(page)).active).toBe(false)}
async function xy(page:Page,x:number,y:number){const s=await state(page),b=await page.locator('#canvas').boundingBox();return{x:b!.x+s.ox+x*s.scale,y:b!.y+s.oy-y*s.scale}}
test.beforeEach(async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));(page as any).__errors=errors;page.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());});
test.afterEach(async({page})=>{expect((page as any).__errors,'No uncaught application errors').toEqual([])});
test('login rejects wrong and case-mismatched credentials; protected route redirects',async({page})=>{await page.goto('/#/project/unknown');await expect(page.locator('#login')).toBeVisible();await page.locator('#login').fill('Juralab');await page.locator('#password').fill('juralab');await page.getByRole('button',{name:'Войти',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Неверный');await page.screenshot({path:'test-results/screenshots/auth.png'});await page.locator('#login').fill('juralab');await page.getByRole('button',{name:'Войти',exact:true}).click();await expect(page).toHaveURL(/#\/projects$/)});
test('clean manager, real Konva stage, hidden extension zones',async({page})=>{await project(page);await expect(page.locator('[data-zone=navigation]')).toBeHidden();await expect(page.locator('[data-zone=inspector]')).toBeHidden();await expect(page.locator('.konvajs-content canvas')).toHaveCount(1);await expect(page.locator('#gridStep')).toHaveValue('100');await page.screenshot({path:'test-results/screenshots/editor-empty.png'});await page.getByRole('link',{name:'Smart Home — к проектам'}).click();await expect(page.locator('.project-grid > button').first()).toContainText('Новый проект');await expect(page.getByRole('button',{name:'Открыть Дом 1',exact:true})).toBeVisible();await page.screenshot({path:'test-results/screenshots/projects.png'})});
test('graphical Enter and NumpadEnter commit once; close deactivates; undo redo',async({page})=>{await project(page);await tool(page);await origin(page);await line(page,'ArrowRight',10000);expect((await state(page)).points[1]).toEqual({x:10000,y:0});await line(page,'ArrowUp',8000,'NumpadEnter');await line(page,'ArrowLeft',10000);await page.keyboard.press('c');let s=await state(page);expect(s.contours).toHaveLength(1);expect(s.area).toBe(80);expect(s.perimeter).toBe(36);expect(s.active).toBe(false);await page.mouse.click((await xy(page,3000,3000)).x,(await xy(page,3000,3000)).y);expect((await state(page)).points).toHaveLength(0);await page.locator('#undo').click();expect((await state(page)).contours).toHaveLength(0);await page.locator('#redo').click();expect((await state(page)).contours).toHaveLength(1);await page.screenshot({path:'test-results/screenshots/graphical-contour.png'})});
test('rectangle dimensions then rotation; anchor fixed; special angles',async({page})=>{await project(page);await tool(page,'rectangle');await origin(page);await page.locator('#rectW').fill('10000');await page.locator('#rectW').press('Enter');expect((await state(page)).rect.stage).toBe('height');await page.locator('#rectH').fill('8000');await page.locator('#rectH').press('Enter');await expect(page.locator('#rectAngle')).toBeFocused();let s=await state(page);expect(s.contours).toHaveLength(0);expect(s.rect.stage).toBe('rotation');await page.locator('#rectAngle').fill('45');s=await state(page);expect(s.rectanglePreview[0]).toEqual({x:0,y:0});await expect(page.locator('#rectAngleLabel')).toHaveClass(/special-angle/);await page.screenshot({path:'test-results/screenshots/rectangle-45.png'});await page.locator('#rectAngle').press('Enter');s=await state(page);expect(s.contours).toHaveLength(1);expect(s.area).toBeCloseTo(80,6);expect(s.active).toBe(false)});
test('rectangle Tab, fixed dimension, angle step, numeric exactness',async({page})=>{await project(page);await tool(page,'rectangle');await origin(page);await page.locator('#rectW').fill('8000');await page.locator('#rectW').press('Enter');await page.locator('#canvas').hover({position:{x:200,y:200}});expect((await state(page)).rect.w).toBe(8000);await page.locator('#rectH').fill('6000');await page.locator('#rectH').press('Tab');await expect(page.locator('#rectW')).toBeFocused();await page.locator('#rectW').press('Tab');await page.locator('#rectH').press('Enter');await page.locator('#angleStep').fill('15');await page.locator('#angleStep').press('Enter');expect((await state(page)).angleStep).toBe(15);await page.locator('#rectAngle').fill('22.5');await page.locator('#rectAngle').press('Enter');expect((await state(page)).area).toBeCloseTo(48,6)});
test('settings: grid visibility, step, snapping, ortho, device, zoom',async({page})=>{await project(page);await page.locator('#gridToggle').click();await expect(page.locator('#gridStep')).toBeDisabled();await page.locator('#gridToggle').click();await page.locator('#gridStep').fill('250');await page.locator('#gridStep').press('Enter');expect((await state(page)).step).toBe(250);await page.locator('#snapToggle').click();expect((await state(page)).snap).toBe(false);await page.locator('#orthoToggle').click();expect((await state(page)).ortho).toBe(true);await page.locator('#deviceMode').click();expect((await state(page)).mode).toBe('trackpad');await expect(page.locator('#deviceTrackpad')).toBeVisible();await expect(page.locator('#deviceMouse')).toBeHidden();await page.locator('#zoomValue').fill('175');await page.locator('#zoomValue').press('Enter');expect((await state(page)).scale).toBeCloseTo(.0875,5)});
test('separate contours, blocked interior, labeling, save and full reload',async({page})=>{await project(page);await footprint(page);await tool(page);await page.locator('#originX').fill('5000');await page.locator('#originY').fill('4000');await page.locator('#originY').press('Enter');expect((await state(page)).points).toHaveLength(0);await page.locator('#originX').fill('15000');await page.locator('#originY').fill('0');await page.locator('#originY').press('Enter');await line(page,'ArrowRight',3000);await line(page,'ArrowUp',2000);await line(page,'ArrowLeft',3000);await page.keyboard.press('c');expect((await state(page)).contours).toHaveLength(2);await page.locator('#fit').click();await page.waitForTimeout(300);const q=await xy(page,5000,4000);await page.mouse.dblclick(q.x,q.y);await page.locator('#contourName').fill('Дом');await page.locator('#contourName').press('Enter');expect((await state(page)).contours[0].name).toBe('Дом');await page.locator('#save').click();await page.screenshot({path:'test-results/screenshots/two-contours.png'});await page.getByRole('link',{name:'Smart Home — к проектам'}).click();await page.getByRole('button',{name:'Открыть Дом 1',exact:true}).click();expect((await state(page)).contours).toHaveLength(2);await page.reload();await expect(page.locator('#canvas canvas')).toBeVisible();expect((await state(page)).contours[0].name).toBe('Дом');expect((await state(page)).active).toBe(false)});
test('temporary points menu and midpoint of edge',async({page})=>{await project(page);await footprint(page);await tool(page);await page.keyboard.press('p');await expect(page.locator('#pointMenu')).toBeVisible();await expect(page.locator('#pointMenu button:not([disabled])')).toHaveCount(5);await expect(page.locator('#pointMenu button[disabled]')).toHaveCount(13);await page.screenshot({path:'test-results/screenshots/temporary-points.png'});await page.locator('[data-point=midpoint]').click();const q=await xy(page,4000,0);await page.mouse.click(q.x,q.y);expect((await state(page)).points[0]).toEqual({x:5000,y:0})});
test('edge and point inference remain independent',async({page})=>{await project(page);await footprint(page);await tool(page);await origin(page,15000,0);let q=await xy(page,5000,8000);await page.keyboard.down('Alt');await page.mouse.click(q.x,q.y);await page.keyboard.up('Alt');q=await xy(page,10000,8000);await page.keyboard.down('Alt');await page.mouse.click(q.x,q.y);await page.keyboard.up('Alt');const s=await state(page);expect(s.inference.edge).not.toBeNull();expect(s.inference.points.length).toBeGreaterThan(0);expect(s.points).toHaveLength(1)});
test('route teardown removes keyboard handlers and dialogs',async({page})=>{await project(page);await footprint(page);await page.locator('#save').click();for(let i=0;i<3;i++){await page.getByRole('link',{name:'Smart Home — к проектам'}).click();await page.getByRole('button',{name:'Открыть Дом 1',exact:true}).click();await expect(page.locator('#canvas canvas')).toHaveCount(1);}await tool(page);await origin(page,15000,0);await line(page,'ArrowRight',1000);expect((await state(page)).points).toHaveLength(2);await page.getByRole('button',{name:'Документация',exact:true}).click();await page.keyboard.press('ArrowUp');await expect(page.locator('#helpDialog')).toBeVisible();await page.getByRole('button',{name:'Закрыть документацию'}).click();expect((await state(page)).points).toHaveLength(2)});
test('logout protects saved routes',async({page})=>{await project(page);await page.getByRole('button',{name:'Аккаунт',exact:true}).click();await page.getByRole('button',{name:'Выйти',exact:true}).click();await expect(page.locator('#login')).toBeVisible();await page.goto('/#/projects');await expect(page.locator('#login')).toBeVisible()});
test('mobile layout keeps drawing canvas and rotation controls reachable',async({page})=>{await page.setViewportSize({width:390,height:844});await project(page);await tool(page,'rectangle');await origin(page);await page.locator('#rectW').fill('10000');await page.locator('#rectW').press('Enter');await page.locator('#rectH').fill('8000');await page.locator('#rectH').press('Enter');await expect(page.locator('#rectAngle')).toBeVisible();await expect(page.locator('#angleStep')).toBeVisible();const b=await page.locator('#canvas').boundingBox();expect(b!.height).toBeGreaterThan(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'test-results/screenshots/mobile-rotation.png'})});
