import {test,expect,Page} from '@playwright/test';
async function state(p:Page){await p.waitForFunction(()=>!!(window as any).smartHomeEditor);return p.evaluate(()=>(window as any).smartHomeEditor.getState());}
async function xy(p:Page,x:number,y:number){await expect.poll(async()=>{const s=await state(p),b=await p.locator('#canvas').boundingBox();return Math.abs(s.w-b!.width);}).toBeLessThan(1);const s=await state(p),b=await p.locator('#canvas').boundingBox();return {x:b!.x+s.ox+x*s.scale,y:b!.y+s.oy-y*s.scale};}
async function click(p:Page,x:number,y:number){const q=await xy(p,x,y);await p.mouse.click(q.x,q.y);}
async function move(p:Page,x:number,y:number){const q=await xy(p,x,y);await p.mouse.move(q.x,q.y);}
async function rect(p:Page,x:number,y:number,w:number,h:number){await p.locator('#contourTool').click();await p.locator('#graphicalTool').click();await p.locator('#originX').fill(String(x));await p.locator('#originY').fill(String(y));await p.locator('#originY').press('Enter');for(const [key,n] of [['ArrowRight',w],['ArrowUp',h],['ArrowLeft',w]] as const){await p.keyboard.press(key);await p.locator('#lineLength').fill(String(n));await p.locator('#lineLength').press('Enter');}await p.keyboard.press('c');}
async function setup(p:Page,references=false){await p.goto('/');await p.locator('#login').fill('juralab');await p.locator('#password').fill('juralab');await p.getByRole('button',{name:'Войти',exact:true}).click();await p.getByRole('button',{name:'Новый проект',exact:true}).click();await state(p);await rect(p,0,0,10000,8000);if(references)await rect(p,-5000,10000,6000,3000);await p.locator('#fit').click();await click(p,5000,4000);await expect(p.locator('sh-contour-inspector')).toBeVisible();await xy(p,0,0);}
async function arm(p:Page,kind:string){await click(p,kind==='edge'?4000:kind==='insert'?5000:0,8000);expect((await state(p)).operation.kind).toBe(kind);}
async function temp(p:Page,mode:string){await p.keyboard.press('p');await expect(p.locator('#pointMenu')).toBeVisible();await p.locator(`[data-point="${mode}"]`).click();expect((await state(p)).temporary.mode).toBe(mode);}
test.beforeEach(async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));(page as any).errors=errors;page.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());});
test.afterEach(async({page})=>expect((page as any).errors).toEqual([]));
test('move vertex on canvas with live preview, atomic commit, undo and redo',async({page})=>{await setup(page);const before=(await state(page)).contours[0].points;await arm(page,'vertex');await move(page,-2000,10000);expect((await state(page)).contours[0].points).toEqual(before);await page.screenshot({path:'test-results/screenshots/vertex-preview.png'});await page.keyboard.press('Enter');expect((await state(page)).contours[0].points[3]).toEqual({x:-2000,y:10000});await page.locator('#undo').click();expect((await state(page)).contours[0].points).toEqual(before);await page.locator('#redo').click();expect((await state(page)).contours[0].points[3]).toEqual({x:-2000,y:10000});});
test('drag edge keeps it parallel and changes just its endpoints',async({page})=>{await setup(page);const a=await xy(page,4000,8000),b=await xy(page,4000,10000);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:4});expect((await state(page)).contours[0].points[2]).toEqual({x:10000,y:8000});await page.mouse.up();expect((await state(page)).operation).toBeNull();expect((await state(page)).contours[0].points).toEqual([{x:0,y:0},{x:10000,y:0},{x:10000,y:10000},{x:0,y:10000}]);});
test('plus handle inserts one vertex with exact arrow distance',async({page})=>{await setup(page);await arm(page,'insert');await page.keyboard.press('ArrowUp');await page.locator('#operationDistance').fill('2100');await move(page,9000,3000);expect((await state(page)).operation.projection[3]).toEqual({x:5000,y:10100});expect((await state(page)).contours[0].points).toHaveLength(4);await page.locator('#operationDistance').press('Enter');expect((await state(page)).contours[0].points).toHaveLength(5);await page.screenshot({path:'test-results/screenshots/inserted-vertex.png'});});
test('Shift-click inserts at any location and Escape never mutates the contour',async({page})=>{await setup(page);await page.keyboard.down('Shift');await click(page,3000,8000);await page.keyboard.up('Shift');expect((await state(page)).operation.base).toEqual({x:3000,y:8000});await move(page,3000,12000);await page.keyboard.press('Escape');expect((await state(page)).contours[0].points).toHaveLength(4);expect((await state(page)).operation).toBeNull();});
test('self crossing and overlap reject an edit without writing history',async({page})=>{await setup(page);await arm(page,'vertex');const s=await state(page);await move(page,15000,4000);await page.keyboard.press('Enter');expect((await state(page)).contours).toEqual(s.contours);expect((await state(page)).history).toBe(s.history);expect((await state(page)).operation.error).toBeTruthy();await page.keyboard.press('Escape');});
for(const kind of ['vertex','edge','insert'])for(const mode of ['midpoint','twoPoints','lines','area','edge']){
 test(`${kind} edit keeps temporary resolver ${mode}`,async({page})=>{await setup(page,true);await arm(page,kind);const before=(await state(page)).contours[0].points;await temp(page,mode);
  if(mode==='midpoint')await click(page,-3500,10000);
  if(mode==='twoPoints'){await click(page,-5000,10000);await click(page,1000,10000);}
  if(mode==='lines'){await click(page,-3500,10000);await click(page,-5000,11000);}
  if(mode==='area'){const a=await xy(page,-5300,10300),b=await xy(page,-4700,9700);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y);await page.mouse.up();await page.keyboard.press('Enter');}
  if(mode==='edge'){await click(page,-3500,10000);await click(page,-2000,11000);}
  const s=await state(page);expect(s.temporary).toBeNull();expect(s.operation).toBeNull();expect(s.contours[0].points).not.toEqual(before);expect(s.contours).toHaveLength(2);
  expect(s.contours[0].points).toHaveLength(kind==='insert'?5:4);
 });
}
test('temporary cancellation preserves the outer edit and its original geometry',async({page})=>{await setup(page,true);await arm(page,'vertex');const before=(await state(page)).contours;await temp(page,'lines');await click(page,-3500,10000);await page.keyboard.press('Escape');expect((await state(page)).temporary).toBeNull();expect((await state(page)).operation.kind).toBe('vertex');expect((await state(page)).contours).toEqual(before);await page.keyboard.press('Escape');expect((await state(page)).operation).toBeNull();});
test('edit retains independent edge and vertex inference with auxiliary axes',async({page})=>{await setup(page,true);await arm(page,'vertex');await page.keyboard.down('Alt');await click(page,-3500,13000);await page.keyboard.up('Alt');const edge=(await state(page)).inference.edge;expect(edge).not.toBeNull();await page.keyboard.down('Alt');await click(page,1000,10000);await page.keyboard.up('Alt');await move(page,980,8010);const s=await state(page);expect(s.inference.edge).toEqual(edge);expect(s.inference.points.length).toBeGreaterThan(0);expect(s.contours[0].points[3]).toEqual({x:0,y:8000});await page.screenshot({path:'test-results/screenshots/edit-inference.png'});});
test('mobile inspector gives canvas space without losing selected contour',async({page})=>{await page.setViewportSize({width:390,height:844});await setup(page);const id=(await state(page)).selectedId;await page.getByRole('button',{name:'Редактировать на холсте',exact:true}).click();await expect(page.locator('sh-contour-inspector')).toBeHidden();expect((await state(page)).selectedId).toBe(id);await page.locator('#fit').click();await arm(page,'vertex');await page.keyboard.press('ArrowLeft');await page.locator('#operationDistance').fill('1000');await page.locator('#operationDistance').press('Enter');expect((await state(page)).contours[0].points[3]).toEqual({x:-1000,y:8000});});
